apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: creative-studio-stage
nameSuffix: -stage

resources:
  - ../../base

replicas:
  - name: creative-studio
    count: 3

secretGenerator:
  - name: creative-studio-secrets
    envs:
      - .env.secret

patches:
  - path: service-patch.yaml

generatorOptions:
  disableNameSuffixHash: true
