name: Production CI/CD

on:
  push:
    branches: [ "prod" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:master
          config-inline: |
            [registry."13.200.24.3"]
              http = true
              insecure = true

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: 13.200.24.3
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and Push to Harbor
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            13.200.24.3/creative-studio-app/creative-studio-prod:${{ github.sha }}
            13.200.24.3/creative-studio-app/creative-studio-prod:latest

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: yashparmar-inventyv/Timoni-creative-studio
          token: ${{ secrets.GITOPS_REPO_TOKEN }}
          path: gitops-repo

      - name: Update Digest in Timoni Values
        run: |
          HARBOR_DIGEST="${{ steps.docker_build.outputs.digest }}"
          cd gitops-repo
          sed -i "s|digest:.*|digest:  \"$HARBOR_DIGEST\"|g" modules/creative-studio/values-prod.cue
          sed -i 's/tag:  *".*"/tag:  ""/g' modules/creative-studio/values-prod.cue
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add modules/creative-studio/values-prod.cue
          
          if ! git diff --staged --quiet; then
            git commit -m "chore(prod): update image digest to $HARBOR_DIGEST"
            git push
          fi